#!/bin/sh

. /etc/uictpl.conf

echo
echo "Created from Ubuntu (${UIC_RELEASE}) on ${UIC_CREATION_TIMESTAMP} using"
echo " - UIC (Unified Installation Creator) ${UIC_CREATION_VERSION}"
echo " - ${UIC_SRCNAME} ${UIC_SRCVERSION} uic template"
echo
echo " * Documentation: http://www.ubuntu.com/server"
echo
