#!/bin/bash
#
# (c) 2012-2015 YeaSoft Int'l - Leo Moll
#
# uic hook:	post_customization
# called by:	uic_create, uic_build, uic_upgrade
#
# This hook will be called by several commands after making any customizations
# (file copies and deletions) to the installation environment in $TARGET

# Newer versions of the OpenSSH package do enforce root login
# with key base dauthentication or disable it at all. We want to
# make sure root can login via SSH also with password. The admin
# can change this later on.
if [ -f "${TARGET}/chroot/etc/ssh/sshd_config" ]; then
	sed 	-i \
		-e 's/^[[:space:]]*PermitRootLogin[[:space:]]*.*$/PermitRootLogin yes # UIC:Modified without-password/' \
		"${TARGET}/chroot/etc/ssh/sshd_config"
fi
